[workspace]
members = [
    "other",
    "other_lib"
]

[workspace.package]
version = "0.1.0"
description = "Example in a workspace"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.11.2"
dojo = { path = "../../dojo" }
dojo_macros = { path = "../../macro" }
