[package]
cairo-version = "=2.11.2"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.3.1"

[dependencies]
starknet = "=2.11.2"
dojo_macros = { path = "../macro" }

[lib]

[[target.starknet-contract]]
sierra = true
