[package]
name = "dojo_other_library"
description = "Simple library in a workspace"
edition.workspace = true
version = "0.1.0"

[dependencies]
starknet.workspace = true
dojo.workspace = true
dojo_macros.workspace = true

[lib]
